### PR TITLE
add optional date param to country API

### PR DESCRIPTION
**Pull request by clearsense**
Need testing

### CODE REVIEW

**Comment by clearsense** [comment]
@xming13 thanks for merge and fix! When new code will be deployed on production, so I can use new date param?

**Comment by xming13** [comment]
Hi @clearsense, it is on production, you can use it.

**Comment by clearsense** [comment]
> Hi @clearsense, it is on production, you can use it.

I tried it like this, but seems like date param don't affect results
http://api.coronatracker.com/v2/analytics/country?date=2020-03-15

**Comment by xming13** [comment]
Hi @clearsense, you made the changes for 
http://api.coronatracker.com/analytics/country?date=2020-03-15
which is different from v2.

**Comment by clearsense** [comment]
> Hi @clearsense, you made the changes for
> http://api.coronatracker.com/analytics/country?date=2020-03-15
> which is different from v2.

I see. How do you think, it's usefull to add same param to v2? I could make another PR.

**Comment by xming13** [comment]
@clearsense The frontend is not using the date filter so it is not useful for now

**Comment by clearsense** [comment]
> @clearsense The frontend is not using the date filter so it is not useful for now

But in v2 country codes are provided, it's nice to have for our project, so I will PR this, if you don't mind.

**Pull request merged**
