### PR TITLE
Add API prefix

### PR DESCRIPTION
**Pull request by d30jeff**

### CODE REVIEW

**Comment by xming13** [comment]
@d30jeff Hi possible to keep existing routes so that it does not break existing app that are currently consuming the API. We can remove it after all the apps change to the versioned API endpoints.

**Comment by d30jeff** [comment]
@xming13 Yup, no problem. Let's stick with the existing routes

**Comment by xming13** [comment]
@d30jeff In case I was not clear, what I mean is to keep the existing routes while you add the v1 routes so that we can merge and will not break existing apps that are using the API.

**Comment by xming13** [comment]
No longer relevant now.

**Pull request closed without merging**
